# -*- coding: utf-8 -*-
"""The meta schema must be generated, not remembered.

On one measured run ten of thirteen sub-agents wrote `{"name": ..., "type":
...}` where the schema wants `{"source": ..., "target_proposal": ...}`, and
`prepare-merge` quarantined every one of those files. The observations were
made and then discarded — which is indistinguishable, from the outside, from
sub-agents that observed nothing at all.

The term table and the neighbour context are generated by a command and
pasted. This makes the meta schema the third such block, built from the field
tuples the validator checks against, so a prompt that describes a shape the
validator rejects cannot be written.
"""
import json
import os
import subprocess
import sys
import unittest
from pathlib import Path

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = Path(HERE).parent
sys.path.insert(0, os.path.join(str(REPO), "scripts"))

import meta                                                      # noqa: E402

SKILL = REPO / "SKILL.md"


class PromptBlockTests(unittest.TestCase):

    def setUp(self):
        self.block = meta.prompt_block()

    def test_it_names_every_required_field_of_every_array(self):
        """Generated from REQUIRED_FIELDS, so this cannot drift."""
        for array, fields in meta.REQUIRED_FIELDS.items():
            self.assertIn(array, self.block, "%s is not described" % array)
            for field in fields:
                self.assertIn('"%s"' % field, self.block,
                              "%s.%s is required but the prompt never names "
                              "it, so a sub-agent has to guess" % (array, field))

    def test_the_validator_and_the_prompt_share_one_source_of_truth(self):
        # If someone re-inlines the tuples in validate_meta, this notices.
        source = (REPO / "scripts" / "meta.py").read_text(encoding="utf-8")
        self.assertIn("REQUIRED_FIELDS[", source,
                      "validate_meta must read REQUIRED_FIELDS, or the "
                      "prompt and the validator can disagree")

    def test_it_forbids_the_chunk_id_field(self):
        self.assertIn("chunk_id", self.block)
        self.assertIn("Do NOT include", self.block)

    def test_it_says_an_empty_meta_is_correct(self):
        self.assertIn("empty", self.block.lower())

    def test_it_demands_a_verbatim_evidence_quote(self):
        self.assertIn("VERBATIM", self.block)
        self.assertIn("drop the item", self.block)

    def test_it_lists_the_valid_confidence_values(self):
        for value in meta.VALID_ATTRIBUTE_CONFIDENCES:
            self.assertIn(value, self.block)

    def test_a_block_shaped_meta_actually_validates(self):
        """Round-trip: build a file the way the block describes, validate it."""
        data = {"schema_version": 1, "new_entities": [], "used_term_sources": [],
                "alias_hypotheses": [], "attribute_hypotheses": [],
                "conflicts": []}
        for array, fields in meta.REQUIRED_FIELDS.items():
            item = {}
            for field in fields:
                item[field] = ("a quote from the chunk" if field == "evidence"
                               else "x")
            if array == "attribute_hypotheses":
                item["confidence"] = meta.VALID_ATTRIBUTE_CONFIDENCES[0]
            data[array] = [item]
        meta.validate_meta(data, "<test>")      # must not raise

    def test_a_meta_using_invented_field_names_is_rejected(self):
        """The exact failure this block exists to prevent."""
        data = {"schema_version": 1,
                "new_entities": [{"name": "Triton", "type": "software",
                                  "evidence": "a quote"}],
                "alias_hypotheses": [], "attribute_hypotheses": [],
                "used_term_sources": [], "conflicts": []}
        with self.assertRaises(Exception):
            meta.validate_meta(data, "<test>")


class CliTests(unittest.TestCase):

    def test_the_command_prints_the_block(self):
        out = subprocess.run(
            [sys.executable, str(REPO / "scripts" / "meta.py"), "prompt-block"],
            capture_output=True, text=True, encoding="utf-8")
        self.assertEqual(out.returncode, 0, out.stderr)
        self.assertIn("target_proposal", out.stdout)

    def test_it_survives_a_console_that_cannot_spell_an_em_dash(self):
        r"""The block prints an em dash. A Windows console under a Korean
        locale encodes stdout as cp949, which has no character for it, and the
        command died with UnicodeEncodeError. Eight other scripts here carry a
        UTF-8 stdout guard; this one did not.

        It hid because the guard was supplied from outside: every invocation
        that passed had PYTHONIOENCODING set in its environment, so the suite
        went green from one shell and red from another with no code between.

        Forced to ASCII rather than cp949, so this reproduces on the Ubuntu CI
        as readily as on the machine that found it.
        """
        env = dict(os.environ, PYTHONIOENCODING="ascii")
        out = subprocess.run(
            [sys.executable, str(REPO / "scripts" / "meta.py"), "prompt-block"],
            capture_output=True, env=env)
        self.assertEqual(out.returncode, 0,
                         out.stderr.decode("utf-8", "replace"))
        self.assertIn(b"target_proposal", out.stdout)


class WorkflowWiringTests(unittest.TestCase):
    """A generated block nobody is told to generate is a block nobody pastes."""

    def setUp(self):
        self.skill = SKILL.read_text(encoding="utf-8")

    def test_the_skill_tells_you_to_generate_it(self):
        self.assertIn("meta.py prompt-block", self.skill,
                      "SKILL.md must instruct generating the meta block, the "
                      "same way it does the term table")

    def test_it_sits_with_the_other_generated_blocks(self):
        for command in ("glossary.py print-terms-for-chunk",
                        "chunk_context.py", "meta.py prompt-block"):
            self.assertIn(command, self.skill)

    def test_the_glossary_step_covers_homographs(self):
        # 정렬 meant both "sorted" and "aligned" in one paper because only one
        # of the two source terms was ever in the glossary.
        self.assertIn("homograph", self.skill.lower(),
                      "the terminology policy must tell you to give a "
                      "homograph both of its source terms")


if __name__ == "__main__":
    unittest.main()
